### ISSUE TITLE
Ingest Kids First studies into D3b Warehouse

### ISSUE THREAD

**Issue by znatty22** [d3b-center/clinical-data-flow#33]
DataOps team wants to copy over studies from Kids First postgres db to D3b postgres db. 

Meen created a CLI tool to do this, but still needs to provide support to DataOps users, fix any bugs, etc. 

Meen help DataOps deploy this as an automated (nightly?) process.

**Comment by znatty22** [comment]
@liberaliscomputing wherever you created the script for this, can you add a link to that PR? The link should point to this issue. I'd like to close this issue.

**Comment by liberaliscomputing** [comment]
@znatty22, here is the link to the repo: https://github.com/d3b-center/d3b-warehouse-general/tree/feature/ingest/kf-dataservice
I didn't create a PR to the master branch since DataOps isn't sure yet if that repo will curate such scripts. Per the automated deployment of this ETL, please refer to the issues here: https://github.com/d3b-center/d3b-warehouse-general/issues

**Comment by znatty22** [comment]
Closing since this is complete.
